# Generated by Django 4.2 on 2024-04-20 18:17

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('categories', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Students'), (2, 'High Schools'), (3, 'Classes'), (4, 'Misc.'), (5, 'Instructors')], max_length=100)),
            ],
            options={
                'unique_together': {('name', 'categories')},
            },
        ),
    ]
