# Generated by Django 4.2 on 2024-04-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingrecord',
            name='app',
            field=models.CharField(default='cis', max_length=100),
        ),
    ]
