# Generated by Django 4.2 on 2026-02-25 15:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_settingrecord_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingrecord',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Students'), ('2', 'High Schools'), ('3', 'Classes'), ('4', 'Misc.'), ('5', 'Instructors')], max_length=100),
        ),
    ]
